// Frontend Development/sanjaim/handson_08/student-portal-vue/src/components/Header.vue
<script setup>
import { RouterLink } from 'vue-router'
import { useEnrollmentStore } from '../stores/enrollment'

const enrollmentStore = useEnrollmentStore()
</script>

<template>
  <header class="header">
    <h1 class="title">Student Portal</h1>
    <nav>
      <ul class="nav-list">
        <li><RouterLink to="/">Home</RouterLink></li>
        <li><RouterLink to="/courses">Courses</RouterLink></li>
        <li><RouterLink to="/profile">Profile</RouterLink></li>
        <li class="enrolled">Enrolled Course: {{ enrollmentStore.enrolledCourses.length }}</li>
      </ul>
    </nav>
  </header>
</template>

<style scoped>
.header {
  padding: 20px 40px;
  display: flex;
  justify-content: space-between;
  align-items: center;
  background-color: #2c3e50;
  color: #fff;
}

.title {
  font-size: 1.5rem;
  margin: 0;
}

.nav-list {
  list-style: none;
  display: flex;
  gap: 30px;
  padding: 0;
  margin: 0;
  align-items: center;
}

.nav-list a {
  color: #fff;
  text-decoration: none;
}

.enrolled {
  color: #90cdf4;
  font-weight: bold;
}
</style>

// Frontend Development/sanjaim/handson_06/student-portal-react/src/components/header.jsx
import React from 'react'
import { Link } from 'react-router-dom'

const Header = (props) =>{
return(
  <header style={styles.header}>
    <h1 style={styles.title}>{props.title}</h1>
    <div style={styles.hamburger}> =Menu </div>
    <nav style={styles.nav}>
      <ul style={styles.navList}>
        <li><Link to="/" style={styles.link}>Home</Link></li>
        <li><Link to="/courses" style={styles.link}>Courses</Link></li>
        <li><Link to="/profile" style={styles.link}>Profile</Link></li>
        <li style={styles.enrolled}>Enrolled Course: {props.enrollCount}</li>
      </ul>
    </nav>
  </header>
)
}

const styles = {
    header: {
        padding: "20px 40px",
        display: "flex",
        justifyContent: "space-between",
        alignItems: "center",
        backgroundColor: "#2c3e50",
        color: "#fff",
    },
    title: {
        fontSize: '2rem',
        marginBottom: '10px'
    },
    nav: {
        display: 'block'
    },
    navList: {
        listStyle: 'none',
        display: 'flex',
        gap: '30px',
        alignItems: 'center',
        flexDirection: 'row',
        padding: 0,
        margin: 0
    },
    link: {
        textDecoration: 'none',
        color: '#fff',
        paddingBottom: "5px",
        borderBottom: "2px solid transparent",
        transition: "border-color 0.3s ease",
    },
    hamburger: {
        display: 'none',
        fontSize: '1.2rem',
        cursor: 'pointer'
    },
    enrolled: {
        color: '#90cdf4',
        fontWeight: 'bold'
    }
};

export default Header;
