// Frontend Development/handson_05/student-portal-react/src/components/CourseCard.jsx
import React from 'react';

const CourseCard = ({ name, code, credits, grade, onEnroll }) => {
    return (
        <div style={styles.card}>
            <div style={styles.header}>
                <h3 style={styles.title}>{name}</h3>
                <span style={styles.code}>{code}</span>
            </div>
            
            <div style={styles.details}>
                <p style={styles.text}><strong>Credits:</strong> {credits}</p>
                <p style={styles.badge}><strong>Grade:</strong> {grade}</p>
            </div>
            <button style={styles.button} onClick={onEnroll}>Enroll</button>
        </div>
    );
};

const styles = {
    button:{
        backgroundColor: '#6b7280',
        color: '#ffffff',
        padding: '6px 12px',
        fontSize: '16px',
        fontWeight: 600,
        border: 'none',
        borderRadius: '4px',
        cursor: 'pointer',
        transition: 'background-color 0.2s ease',
        marginTop: '15px'
    },
    card: {
        border: '1px solid #e0e0e0',
        borderRadius: '8px',
        padding: '20px',
        margin: '15px 0',
        backgroundColor: '#ffffff',
        boxShadow: '0 4px 6px rgba(0, 0, 0, 0.05)',
        width: '300px',
        display: 'flex',
        flexDirection: 'column',
        fontFamily: 'sans-serif'
    },
    header: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        borderBottom: '1px solid #f0f0f0',
        paddingBottom: '12px',
        marginBottom: '12px'
    },
    title: {
        margin: 0,
        fontSize: '1.25rem',
        color: '#2c3e50',
        maxWidth: '70%'
    },
    code: {
        backgroundColor: '#edf2f7',
        color: '#4a5568',
        padding: '4px 8px',
        borderRadius: '4px',
        fontSize: '0.85rem',
        fontWeight: 'bold'
    },
    details: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center'
    },
    text: {
        margin: 0,
        color: 'grey',
        fontSize: '0.95rem'
    },
    badge: {
        margin: 0,
        backgroundColor: 'grey',
        color: 'white',
        padding: '4px 10px',
        borderRadius: '12px',
        fontSize: '0.9rem',
        fontWeight: 'bold'
    }
};

export default CourseCard;

// Frontend Development/sanjaim/handson_08/student-portal-vue/src/components/CourseCard.vue
<script setup>
defineProps({
  name: String,
  code: String,
  credits: Number,
  grade: String,
})

defineEmits(['enroll'])
</script>

<template>
  <div class="course-card">
    <div class="course-card-header">
      <h3>{{ name }}</h3>
      <span class="code">{{ code }}</span>
    </div>
    <p><strong>Credits:</strong> {{ credits }}</p>
    <p><strong>Grade:</strong> {{ grade }}</p>
    <button @click="$emit('enroll')">Enroll</button>
  </div>
</template>

<style scoped>
.course-card {
  border: 1px solid #e0e0e0;
  border-radius: 8px;
  padding: 20px;
  background-color: #ffffff;
  box-shadow: 0 4px 6px rgba(0, 0, 0, 0.05);
  display: flex;
  flex-direction: column;
}

.course-card-header {
  display: flex;
  justify-content: space-between;
  align-items: flex-start;
  border-bottom: 1px solid #f0f0f0;
  padding-bottom: 12px;
  margin-bottom: 12px;
}

.course-card-header h3 {
  margin: 0;
  font-size: 1.25rem;
  color: #2c3e50;
}

.code {
  background-color: #edf2f7;
  color: #4a5568;
  padding: 4px 8px;
  border-radius: 4px;
  font-size: 0.85rem;
  font-weight: bold;
}

button {
  margin-top: 15px;
  padding: 6px 12px;
  background-color: #6b7280;
  color: #ffffff;
  border: none;
  border-radius: 4px;
  font-weight: 600;
  cursor: pointer;
}
</style>
